yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'),
    path(
        'create/',
        views.post_create,
        name='post_create'),

    path(
        '',
        views.index,
        name='index'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/fields_comment_form.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
          <small id="{{ form.text.id_for_label }}-help" class="form-text text-muted">
          {{ form.text.help_text|safe }}</small>
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/includes/fields_form.html
{% load user_filters %}
<div class="form-group row my-3 p-3"
   aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
      <span class="required text-danger">*</span>
    {% endif %}
  </label>
  {{ field|addclass:'form-control' }}
  {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}
    </small>
  {% endif %}
</div>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>

      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
          </li>
        
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
          </li>
        
          {% if request.user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
              href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
        
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'posts:change_password' %}active{% endif %}"
              href="<!--  -->">Изменить пароль</a>
            </li>
        
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'auth:logout' %}active{% endif %}" 
              href="{% url 'auth:logout' %}">Выйти</a>
            </li>
        
            <li>
              Пользователь: {{ user.username }}
            </li>
        
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'auth:login' %}active{% endif %}" 
              href="{% url 'auth:login' %}">Войти</a>
            </li>
        
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'auth:signup' %}active{% endif %}" 
              href="{% url 'auth:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>      
</header>

yatube/templates/includes/post_desk.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }} <br>
      {% if not HIDE_AUTHOR_INFO %}  
        <a class="btn btn-info"
         href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
      {% endif %}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% if not HIDE_GROUP_INFO and post.group %}  
    <a class="btn btn-info"
     href="{% url 'posts:group_list' post.group.slug %}">Все посты группы "{{ post.group.title }}"</a><br>
  {% endif %}
  
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>    
  <a class="btn btn-success"
  href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
</article>
{% if not forloop.last %}<hr>{% endif %}