yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'),
    path(
        'create/',
        views.post_create,
        name='post_create'),

    path(
        '',
        views.index,
        name='index'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()
NUMBER_OF_LETTERS = 15


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы')
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор группы')
    description = models.TextField(
        verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата написания')
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Пост',
        related_name='posts')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:NUMBER_OF_LETTERS]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='К посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата написания')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Автор')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Введите текст поста',
            'group': 'Укажите группу',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Введите текст комментария',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow, User


def page_inator(posts, request):
    paginator = Paginator(posts, settings.OBJ_ON_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(60 * 15)
def index(request):
    post_list = Post.objects.select_related("author", "group")
    page_obj = page_inator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = page_inator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = page_inator(posts, request)
    following_list = Follow.objects.filter(
        user=request.user.id, author=author.id).exists()

    following = request.user.is_authenticated and following_list
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all

    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if post.author == request.user:

        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post.pk)

        context = {
            'form': form,
            'is_edit': True,
            'post': post
        }
        return render(request, 'posts/create_post.html', context)
    else:
        return redirect('posts:post_detail', post.pk)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    followers = request.user.follower.values('author')
    post_list = Post.objects.select_related(
        "author", "group").filter(
            author__in=followers, author__following__user=request.user)
    page_obj = page_inator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(author=author, user=user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактирование
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактирование
             {% else %}
              Новый пост
            {% endif %}             
          </div>
          <div class="card-body">                  
            {% if form.errors %}
              {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            {% if is_edit %}
              <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
            {% else %}
              <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
            {% endif %}
            {% csrf_token %}
            {% for field in form %} 
              {% include 'includes/fields_form.html' %}
            {% endfor %}

             <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% cache 20 follow_page with page_obj %}
  {% block content %}
    {% with follow=True %}
      {% include 'posts/includes/switcher.html' %} 
    {% endwith %}
    <h1> Избранные авторы </h1> 
    {% for post in page_obj %}
      {% include 'includes/post_desk.html' %}
    {% endfor %}
  
    {% include 'posts/includes/paginator.html' %}

  {% endblock %}
{% endcache %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group }}
{% endblock %}
{% block content %}
  <h1>{{ group }}</h1>
  <p>{{ group.description }}</p>
  {% with HIDE_GROUP_INFO=True %}
    
    {% for post in page_obj %}
      {% include 'includes/post_desk.html' %} 
    {% endfor %}
    
  {% endwith %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% cache 20 index_page with page_obj %}
  {% block content %}
  {% with index=True %}
    {% include 'posts/includes/switcher.html' %} 
  {% endwith %}
  <h1>Последние публикации на сайте </h1> 
    {% for post in page_obj %}
      {% include 'includes/post_desk.html' %}
    {% endfor %}
  
    {% include 'posts/includes/paginator.html' %}

  {% endblock %}
{% endcache %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
 
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}  

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
         </li>
        {% if post.group %}   
          <li class="list-group-item">
            Группа: {{ post.group.slug }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.all.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
    </article>
  </div>
  {% if post.author == request.user %}
    <a href="{% url 'posts:post_edit' post.id %}">
      Редактирование
    </a> 
  {% endif %}
  {% include 'includes/fields_comment_form.html' %}
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}    
  Профайл пользователя {{ user.get_full_name }} 
{% endblock %}
{% block content %}          
  <h1>Все посты пользователя {{ user.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3> 
    {% if request.user != author and request.user.is_authenticated %}
      {% include 'posts/includes/subscribe_button.html' %} 
    {% endif %}
  {% with HIDE_AUTHOR_INFO=True %}

    {% for post in page_obj %}
      {% include 'includes/post_desk.html' %} 
    {% endfor %}    
    
  {% endwith %}
  {% include 'posts/includes/paginator.html' %}  
{% endblock %}